CREATE TABLE announcements (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  announcement_events_id INTEGER
    REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  "date" DATE NOT NULL,
  "time" TIME,
  title TEXT NOT NULL,
  "location" TEXT,
  "address" TEXT,
  "description" TEXT,
  "url" TEXT,
  modified TIMESTAMP NOT NULL DEFAULT now()
);
