CREATE TABLE contact (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contact_events_id INTEGER
    REFERENCES events(id) ON DELETE CASCADE NOT NULL,
  church TEXT NOT NULL,
  logo TEXT NOT NULL,
  "connect" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  website TEXT NOT NULL,
  pastor_name TEXT NOT NULL,
  pastor_title TEXT NOT NULL,
  pastor_email TEXT NOT NULL,
  associate_name TEXT,
  associate_title TEXT,
  associate_email TEXT,
  modified TIMESTAMP NOT NULL DEFAULT now()
);
